local library = loadstring(game:HttpGet("https://raw.githubusercontent.com/PitchyATree/roblox-exploit-library/main/turtle%20library%20red%20version"))()
local window = library:Window("PitchHub - SLJO")

-- Variables globales
local toggles = {
    items = false,
    move = false,
    rebirth = false,
    jump = false
}

-- Fonction : téléporte les items au joueur
local function teleportItems()
    local player = game.Players.LocalPlayer
    local root = player.Character and player.Character:FindFirstChild("HumanoidRootPart")
    if not root then return end

    for _, item in pairs(workspace:WaitForChild("Checkpoints"):GetChildren()) do
        if item:IsA("BasePart") or item:IsA("Model") then
            local part = item:IsA("Model") and item:FindFirstChildWhichIsA("BasePart")
            if part then
                part.CFrame = root.CFrame
            else
                item.CFrame = root.CFrame
            end
        end
    end
end

-- Téléportation automatique
task.spawn(function()
    while task.wait(0.1) do
        if toggles.items then
            teleportItems()
        end
    end
end)
---- Script generated by TurtleSpy, made by Intrer#0421

--game:GetService("ReplicatedStorage").StageTransfer:FireServer("up")
-- Rebirth auto
task.spawn(function()
    while task.wait(0) do
        if toggles.rebirth then
            -- Script generated by TurtleSpy, made by Intrer#0421

game:GetService("ReplicatedStorage").RebirthEvent:FireServer()
            
        end
    end
end)

task.spawn(function()
    while task.wait(0) do
        if toggles.move then
            -- Script generated by TurtleSpy, made by Intrer#0421

game:GetService("ReplicatedStorage").StageTransfer:FireServer("up")
            
        end
    end
end)

-- Auto-jump
task.spawn(function()
    while task.wait(0.1) do
        if toggles.jump then
            local hum = game.Players.LocalPlayer.Character and game.Players.LocalPlayer.Character:FindFirstChildOfClass("Humanoid")
            if hum then
                hum:ChangeState(Enum.HumanoidStateType.Jumping)
            end
        end
    end
end)

-- UI Toggles
window:Toggle("Pads", false, function(bool)
    toggles.items = bool
end)

window:Toggle("Move", false, function(bool)
    toggles.move = bool
end)

window:Toggle("Rebirth", false, function(bool)
    toggles.rebirth = bool
end)

window:Toggle("Jump", false, function(bool)
    toggles.jump = bool
end)

window:Button("anti afk", function()  
local vu = game:GetService("VirtualUser")
game:GetService("Players").LocalPlayer.Idled:connect(function()
   vu:Button2Down(Vector2.new(0,0),workspace.CurrentCamera.CFrame)
   wait(1)
   vu:Button2Up(Vector2.new(0,0),workspace.CurrentCamera.CFrame)
end)
end)
